# 정확도가 높은 예측모델을 구축하는 학습기 선택
이제 퍼즐컬렉션은 큰 문제없이 회사의 주요 수익원으로 정착되었습니다.<br>
보통 비즈니스에서 안정 상황이라 함은 유저가 서비스를 이용하면서 느끼는 감정을 기획자가 파악할 수 있는 상태를 말하며, 이렇게 서비스가 안정 상황에 접어들면 유저들에게 더 높은 만족도를 제공하기 위한 서비스나 실험적인 계획을 시도하게 됩니다.<br>
퍼즐컬렉션에서도 운영이 안정되고 난 후부터는 게임이용자의 더 큰 즐거움을 위해 여러가지 기획을 논의한 후, 실시한 기획에 대해서는 데이터 검증을 통해 그 기획이 좋았는지 나빴는지 판단하는 식으로 양호한 비즈니스 검증 (PDCA) 사이클 [개선->기획->실시->검증->개선->...]을 실시할 수 있게 되었습니다.<br>

그런 와중에 게임 안에서 유저끼리 팀을 이루어서 팀원끼리 힘을 모아 강력한 보스를 제압하는 이벤트를 어떤 기획자가 제출하였습니다.<br>
팀플레이에서 중요한 것은 '어떻게 팀을 편성하는가?' 입니다. 처음에는 유저끼리 직접 연락해서 팀을 만드는 방법을 생각했었는데, 팀플레이를 보다 즐겁게 할 수 있는 편성 방법을 모색하고 싶다며 기획자로부터 연락이 왔습니다.<br>
그래서 데이터 분석을 활용해서 팀플레이의 즐거움을 극대화할 수 있는 편성 방법을 검토하기로 했습니다.<br>
 ## 현실의 모습 / 이상적인 모습
* 현실의 모습 : 팀 편성 방법이 최적화되지 않은 상황
* 이상적인 모습 : 팀 편성 방법이 최적화된 상태

이번 분석도 겉으로 크게 드러난 문제점을 해결해야 하는 상황은 아닙니다. 유저들이 팀플레이를 보다 즐겁게 느낄 수 있도록 팀을 편성하는 방법을 데이터 분석을 활용해서 찾아내고자 하는 것입니다.<br>
그렇다면 '팀플레이의 즐거움'이란 과연 무엇일까요? '즐거움'과 같이 사람마다 '즐거움'은 다른 이미지를 떠올릴 수 있기에 먼저 '팀플레이의 즐거움'을 정의해야 합니다.<br>
이를 위해 기획팀과 회의를 가졌고, 다음과 같은 의견을 들을 수 있었습니다.<br>
"유저 입장에서 봤을 땐 어떤 팀에 들어가더라도 팀원들이 같은 시간대에 게임을 이용하지 않으면 혼자 게임하는 것과 다를 바가 없으며, 그렇게 되면 팀플레이의 즐거움을 충분히 느끼지 못할 것이다."<br>
즉, 팀플레이의 즐거움이란 "친구와 실시간으로 같이 싸운다는 감각"일 것입니다.<br>
비슷한 시간대에 게임을 이용하는 사람들끼리 팀을 이룰 수 있도록 한다면 모두 즐겁게 팀전을 즐길 수 있을 것입니다.<br>
그러므로 팀플레이의 즐거움을 '팀 내에서 같은 시간대에 게임을 이용하는 인원수'라고 정의하고, 데이터 분석을 활용해서 같은 시간대에 이용하는 사람들끼리 팀을 만들도록 하는 것이 가능한지 검토해봅시다.

## 분석 스토리 정리
* 목적
    - 가급적 같은 시간대에 게임을 이용하는 유저들끼리 팀을 만들도록 하고 싶다.
* 분석 접근 방법
    - 과거의 게임 이용 상황을 분석해서 유저별로 다음날 게임을 이용할 시간대를 예측한다.
* 액션
    - 분석 결과를 가지고 같은 시간대에 이용할 것 같은 유저끼리 팀을 만들도록 추천한다.

만일 데이터 분석을 한 결과, 유저별로 내일 이용할 시간대를 예측할 수 없다면 이번 기획은 포기해야 할 것입니다.<br>
반대로, 유저별로 내일 이용할 시간대를 예측할 수 있다면 분석 결과를 게임에 반영해서 더 큰 재미를 제공할 수 있을 것입니다.<br>
이것은 서비스 경험이 아무리 많은 사람이라 할지라도 쉽게 제공할 수 있는 것은 아니며, 데이터 분석을 활용하지 않고서는 제공할 수 없는 부가가치라고 할 수 있습니다.<br>

이에 필요한 데이터를 검토하겠습니다.<br>
필요한 데이터는 '각 유저가 내일 게임을 이용할 시간대'를 추측하기 위해 필요한 정보입니다.<br>
각 유저가 지금까지 어떤 시간대에 게임을 이용했는지는 액션로그를 보면 알 수 있습니다.<br>
현 시점에는 각각의 액션이 세세하게 몇 시 몇 분 몇 초에 일어났는지 기록한 상세데이터 혹은 그것을 날짜 단위로 집계한 일차데이터 밖에 존재하지 않습니다.<br>
기획자와 논의한 결과, 1시간 단위로 팀플레이 서비스를 제공하기로 기본방침을 정했습니다.<br>

이를 위해 시간 단위별로 모든 액션수를 집계한 데이터를 중간데이터로 출력시키기로 했습니다.<br>
그 후 모든 액션의 중간데이터를 가지고 과거의 이용 상황과 다음날의 이용 상황간의 상관분석을 실시한 결과, 여러 액션 중 특히 A가 높은 상관을 보였으며, 액션 A를 참고하면 내일 이용할 시간대를 예측할 수 있다는 것을 알게 되었습니다.<br>
그러면 액션A의 중간데이터를 이용해서 시간대가 열에 위치하도록 데이터를 정렬합니다.<br>
데이터가 평일이었는지 휴일이었는지에 따라 영향이 생길 수 있으므로, 과거 7일동안의 데이터를 사용하기로 하고, 시간대별로 액션을 실행했는지 0과 1로 나타냅니다.<br>
우리는 지금 과거의 데이터로 부터 내일을 예측하려 하고 있으며, 목적변수의 '어떤 날'은 설명변수로 제시된 7일의 다음 날(월요일 1~23시) 가 됩니다.

## 데이터 수집과 가공
### 분석에 필요한 데이터 수집

In [158]:

#필요한 라이브러리 불러오기
import pandas as pd
import numpy as np
import warnings
import os
warnings.filterwarnings(action='ignore')
# 평일과 휴일의 영햐을 배제하기 위해 과거 7일 동안의 데이터를 사용하기로 함.
from datetime import datetime
# tsv 파일들을 읽어서 데이터프레임으로 만듭니다.
def readActionHourly(app_name, date_from, date_to):
    date_from = datetime.strptime(date_from, "%Y-%m-%d").date()
    date_to = datetime.strptime(date_to, "%Y-%m-%d").date()
    
    dfs = []
    for day in pd.date_range(date_from, date_to, freq='D'):
        f = f"section10_data/action_hourly/{app_name}/{day.strftime('%Y-%m-%d')}/action_hourly.tsv"
        df = pd.read_csv(f, sep='\t', header=0, dtype={'log_hour': str})
        dfs.append(df)
    
    return pd.concat(dfs, axis=0, ignore_index=True)

# 작성한 함수로 데이터 읽어들이기
action_hourly = readActionHourly("game-01", "2013-08-01", "2013-08-08")

action_hourly.info()        
# log_date : 날짜
# log_hour : 이용시간대
# app_name : 앱 이름
# user_id : 유저 ID
# count : 실시횟수
print("============================================")
action_hourly

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14183 entries, 0 to 14182
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   log_date  14183 non-null  object
 1   log_hour  14183 non-null  object
 2   app_name  14183 non-null  object
 3   user_id   14183 non-null  int64 
 4   count     14183 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 554.1+ KB


log_date log_hour app_name  user_id  count
0      2013-08-01       16  game-01     7339      1
1      2013-08-01       20  game-01     1973     87
2      2013-08-01       10  game-01     1973     30
3      2013-08-01       11  game-01     1973     48
4      2013-08-01       23  game-01       94      3
...           ...      ...      ...      ...    ...
14178  2013-08-08       22  game-01     3193     72
14179  2013-08-08       22  game-01     2229      4
14180  2013-08-08       22  game-01     2887     14
14181  2013-08-08       23  game-01     5312     19
14182  2013-08-08       23  game-01      436     12

[14183 rows x 5 columns]

In [159]:
# 시간대가 열에 오도록 정렬
dates = np.unique(action_hourly['log_date'])
train_list = []

for i in range(len(dates)-1):
    day = dates[i]
    x = action_hourly[action_hourly['log_date'] == day]
    df = pd.pivot_table(x, values='count', index='user_id', columns='log_hour',
                        aggfunc=lambda x: 1 if np.sum(x) >= 7 else 0, fill_value=0)
    
    df.columns = [f'p{i}_{hour}' for hour in range(24)]
    train_list.append(df)

In [160]:
# 설명변수 데이터 작성
# 2013-08-01에 접속하지 않은 유저는 포함하지 않기 위해 left join 이용.
train_df = train_list[0]
for i in range(1, len(train_list)):
    df = train_list[i]
    train_df = pd.merge(train_df, df, on='user_id', how='left')
    train_df = train_df.fillna(0)
train_df

p0_0  p0_1  p0_2  p0_3  p0_4  p0_5  p0_6  p0_7  p0_8  p0_9  ...  \
user_id                                                              ...   
71          0     0     0     0     0     0     0     0     0     0  ...   
78          0     0     0     0     0     0     0     0     0     0  ...   
94          0     0     0     0     0     0     0     0     0     0  ...   
99          0     0     0     0     0     0     0     0     0     0  ...   
131         0     0     0     0     0     0     0     0     0     1  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
9934        0     0     1     1     0     0     0     0     0     0  ...   
9960        0     0     1     1     0     1     1     1     1     1  ...   
9992        0     0     0     0     0     0     0     1     0     0  ...   
9994        1     0     0     0     0     0     0     0     0     0  ...   
9996        0     0     0     0     0     0     0     0     0     0  ...   

         p6_14  p6_15  p6_16  p6_17  p6_18  p6_19  p6_20  p6_21  p6_22  p6_23  
user_id                                                                        
71         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
78         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
94         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
99         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0  
131        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
9934       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
9960       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0  
9992       0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0  
9994       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
9996       0.0    0.0    1.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0  

[535 rows x 168 columns]

In [161]:
# 정답 데이터 작성
ans0 = action_hourly[action_hourly['log_date'] == dates[-1]]

# 시간대가 열에 오도록 정렬
ans = ans0.pivot_table(index='user_id', columns='log_hour', values='count', aggfunc=lambda x: 1 if x.sum() >= 7 else 0)
ans.columns = [f'a_{hour}' for hour in range(24)]
ans = ans.fillna(0)
ans

a_0  a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9  ...  a_14  a_15  \
user_id                                                    ...               
12       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
66       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
72       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   1.0   0.0   
78       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...   0.0   0.0   
97       0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...   0.0   0.0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
9929     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9960     0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  ...   1.0   0.0   
9966     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9992     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   1.0   0.0   
9996     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   1.0   

         a_16  a_17  a_18  a_19  a_20  a_21  a_22  a_23  
user_id                                                  
12        0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
66        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
72        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
97        0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
...       ...   ...   ...   ...   ...   ...   ...   ...  
9929      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9960      0.0   0.0   0.0   0.0   1.0   0.0   1.0   1.0  
9966      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
9992      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
9996      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[588 rows x 24 columns]

In [162]:
# 설명변수 데이터와 정답 데이터 결합하기
# 2013-08-01에 접속하지 않은 유저는 포함하지 않기 위해 left join 이용.
train_data=pd.merge(train_df,ans,on='user_id',how='left')
train_data = train_data.fillna(0)
train_data

p0_0  p0_1  p0_2  p0_3  p0_4  p0_5  p0_6  p0_7  p0_8  p0_9  ...  \
user_id                                                              ...   
71          0     0     0     0     0     0     0     0     0     0  ...   
78          0     0     0     0     0     0     0     0     0     0  ...   
94          0     0     0     0     0     0     0     0     0     0  ...   
99          0     0     0     0     0     0     0     0     0     0  ...   
131         0     0     0     0     0     0     0     0     0     1  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
9934        0     0     1     1     0     0     0     0     0     0  ...   
9960        0     0     1     1     0     1     1     1     1     1  ...   
9992        0     0     0     0     0     0     0     1     0     0  ...   
9994        1     0     0     0     0     0     0     0     0     0  ...   
9996        0     0     0     0     0     0     0     0     0     0  ...   

         a_14  a_15  a_16  a_17  a_18  a_19  a_20  a_21  a_22  a_23  
user_id                                                              
71        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
94        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
99        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
131       1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
9934      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9960      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   1.0  
9992      1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
9994      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9996      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[535 rows x 192 columns]

## 예측모델 작성 순서
1. '규칙성'과 '유사성'의 검증
    어떤 도구를 사용하든 모델을 잘 구축하기 위한 조건은 다음과 같은 것이 필요합니다.
    - 데이터에서 규칙성을 찾을 수 있을 것
    - 데이터에서 유사성을 찾을 수 있을 것<br>

    구체적으로는 데이터 행렬의 열 방향에는 '규칙성'이, 행 방향에는 '유사성'이 존재해야 합니다.<br>
    >즉, 예측모델을 작성할 때 가장 먼저 해야 할 일은 데이터에 규칙성과 유사성이 존재하는지 검증하는 것입니다.<br>

    이번 사례의 경우 규칙성을 찾을 수 없는 경우란 유저들의 게임 이용시간이 어떤 날은 아침에 몰리고 어떤 날은 점심 혹은 저녁에 몰리는 등 완전히 들쭉날쭉한 경우라 하겠습니다.<br>
    또한 유사성이 없는 경우란 어떤 유저는 아침에만 게임을 이용하고, 다른 어떤 유저는 하루 종일 게임을 즐기는 등 전혀 비슷한 점이 없는 경우를 말합니다.<br>
    이렇듯 데이터에 규칙성과 유사성 중 하나라도 결여 되어 있으면 예측모델을 잘 구축하기가 어렵습니다.<br>
    데이터를 검증해서 규칙성과 유사성이 없다고 판단되면 모델 구축을 포기하든가, 데이터를 요약해서 규칙성과 유사성을 어떨게든 노출할 필요가 있습니다.<br>
    '데이터를 요약한다'는 것은, 예를 들어 1일 단위로 데이터를 집계한다거나, 혹은 심야에 반드시 게임을 이용하는 유저 등 특정한 조건을 가지고 데이터를 선별해서 규칙성이나 유사성을 찾아내는 것을 말합니다.
2. 노이즈 제거
    어떤 통계 도구든 기본적으로 노이즈에는 취약한 법입니다.<br>
    어느정도 노이즈에 강한 도구를 쓰더라도, 일반적으로 노이즈를 제거하고 나서 구축해야 보다 좋은 모델을 얻을 수 있습니다.<br>
    앞으로 일어날 일을 잘 설명할 수 있는 우수한 예측모델을 구축해야 함과 동시에, 그 모델이 현실세계와 동떨어져서는 안됩니다.<br>
    비즈니스에서 이용하는 모델 구축에서는 노이즈를 정의내리기 어려울 때가 많아서 예측모델을 구축할 때, 어떤 값을 경계선으로 해서 노이즈를 정의할지 서비스 기획자에게 반드시 확인할 필요가 있습니다.
3. 도구 선택
    지금껏 모든 상황에 가능한 전지전능한 도구가 존재했던것은 아니고, 분석대상에 따라 적합한 도구를 골라서 사용했습니다.<br>
    데이터 분석의 경험을 쌓다보면 기초적인 데이터 검증을 실시할 때 이 데이터는 어떤 도구를 사용하는 것이 좋겠다는 감이 잡히는데, 시간적인 여유가 있다면 가급적 여러 도구를 시험해서 가장 정확도가 높은 것을 골라서 이용하려는 자세가 필요합니다.

### 데이터의 '규칙성'과 '유사성' 검증
액션 A의 1주동안의 데이터에 대해 규격화와 주성분 분석을 실행한 후 k-means 알고리즘으로 클러스터링을 실시했습니다.<br>
- 주말에만 많이 이용하는 '주말형 유저' : 8.1%<br>
- 통근이나 통학 시간에 주로 이용하는 '아침 7시형','아침 8시형' : 19.2%<br>
- 오전시간에 주로 이용하는 '오전형 유저' : 12%<br>
- 23시 혹은 24시 등에 이용하는 '심야형 유저' : 12.8%<br>
- 특정 시간대에 집중하지 않고 골고루 이용하는 '아무때나형 유저' : 47.9%<br>

개개인의 행동로그를 보면 천차만별로 보이지만, 1주 동안의 데이터를 1시간 단위로 놓고 보면 각 유저으 행동은 여섯 종류의 클러스터 어딘가로 분류되며, 클러스터마다 뚜렷한 패턴이 존재하는 데이터 임을 알 수 있습니다.<br>
이렇게 데이터에 규칙성과 유사성의 존재함이 검증되었으므로, 이 행동로그를 가지고 예측모델 작성을 검토하겠습니다.<br>

### 노이즈 제거
기획 담당자와 논의하기 위해 노이즈의 임계값을 잠정적으로 선정합니다.<br>
데이터의 규칙성과 유사성의 검증 결과를 고려해서 '유저들은 전날과 같은 시간대에 다시 게임을 이용한다' 라는 가정을 합니다.<br>
어떤 날의 데이터를 정답 데이터로 두고, '이용한다','이용하지 않는다'를 카테고리 변수라고 했을 때, 예측모델이 해야 할 일은 과거의 행동로그로부터 현재 혹은 미래의 데이터가 어느 카테고리에 속할지 추정하는 것입니다.<br>

이 사례에서 모델을 작성할 때 노이즈가 되는 것은 시간당 기록된 액션로그의 수치가 1 혹은 2 정도인 데이터입니다.<br>
액션로그가 1 혹은 2 정도일 매는 실제 게임을 이용한 것이 아니라. 오작동으로 게임을 실행시켰거나 게임을 하려고 했는데 급한일이 생겨서 관뒀다는 등 우연히 혹은 의도치 않게 로그가 쌍였을 수 있습니다.<br>
유저가 의도하지 않은 동작으로 인해 쌍인 로그가 포함되어 있으면 좋은 예측모델을 구축하기 어려워집니다.<br>
그래서 시간당 액션로그 수치가 작을 때는 노이즈로 간주할 수 있는데, 이때 또한 문제가 되는 것은 그러면 과연 '얼마 이하를 노이즈로 간주할 것인가' 입니다.<br>
아울러 얼마만큼의 과거 행동로그를 살퍼봐야 다음날의 행동을 예측할 수 있는지와 거슬러 올라갈 기간에 대해서도 곰곰이 생각해볼 필요가 있습니다.<br>
예를 들어 어떤 유져가 전날 20시에 게임을 이용하지 않았는데, 전날 하루 데이터만 봐서는 그 유저가 사정이 있어서 우연히 게임을 이용하지 않았는지, 혹은 원래 그 시간대에는 게임을 이용하지 않던 사람인지 알 수 없다는 것입니다.<br>
이들의 최적값을 산출하는 파라미터로서 '시간당 액션횟수의 임계값과 '액션로그를 거슬러 올라갈 기간'이라는 2개의 변수를 실정합 수 있습니다.<br>
'시간당 액션횟수의 임계값'을 1~1000, '액선로그를 거슬러 올라같 기간'을 과거 1~30일로 잡고, 가능한 모든 조합 중 실제 데이터를 가장 잘 설명할 수 있는 조건을 찾아냅니다.<br>

과거 1~30일간의 누적 PV(Page View)수 (유저가 웹서버에 접근한 횟수) 중 '액션횟수의 임계값'을 1~1000으로 분류모델을 작성했을 때의 계산하였습니다.<br>
'최근 3일 동안 이떤 시간대의 누적 액선횟수가 7 이상인지 7 미만인지에 따라 그 다음날 같은 시간대에 게임을 이용할지 하지 않을지' 예측한 모델에서 F1값이 높게 나타난 것을 알 수 있었습니다. 

이렇게 산출된 조건을 게임기획자, 운영자에게 얘기한 결과, 계임 내에서 보너스를 획득할 수 있는 로그인 보너스에 도달할 때까지 대략 5~6PV 정도가 필요
함을 알 수 있었습니다. 또한 최근 3일 동안이라는 조건에 대해서는 근거가 부족하다는 지적이 있었습니다.<br>
그래서 좀 더 조사해본 결과, 이틀 동안은 같은 시간대에 데이터가 0인 경우가 많은 것이 확인되었습니다.<br>
즉, 이틀은 게임을 쉬는 듯하며, 모두 더해 6 이하가 되는 상황은 우연히 들렀다가 남겨진 로그라는 것을 알 수 있었습니다.<br>
그래서 행동로그에서 시간당 7V 미만인 곳은 노이즈로 간주하여 데이터를 0으로 바꾸는 전처리를 실시합니다.

### 이용할 학습기 고르기
이번에는 새로운 기획을 작성할 시간이 며칠 정도 있기 때문에 '로지스틱 회귀','k근방법', '단순베이즈분류기', 'SVM', '랜덤포레스트'라는 카테고리 변수를 예
측하는 학습기 중 대표적인 다섯 종류를 가지고 '과거 7일 동안의 행동로그로부터 다음날 게임을 이용할 시간을 추정'하는 이번 사례에서 가장 큰 효과를 얻을 수 있는 학습기를 고르고자 합니다.<br>
각각의 학습기에 대해 앞에서 설명한 노이즈 전처리를 실시한 3~9일 전의 1주일간의 행동로그를 사용해서, 2일 전에는 몇 시에 게임을 이용했어야 하는지에
대한 예측모델을 구죽합니다.<br>
이것을 역시 전처리해놓은 2~8일 전의 1주일간 행동로그에 적용하여, 어제는 몇 시에 게임을 이용했어야 하는지 추정해서, 실제 데이터와의 일치율을 산출합니다.<br>
먼저 학습기가 잘 동작하도록 하기 위해서는 예측모델의 답이 될 데이터가 같은 정도로 준비되어야 합니다.<br>
이번 사례로 말하자면 온(게임을 이용한) 사람'의 숫자와 '안 온(게임을 이용하지 않은) 사람'의 숫자가 같은 정도로 준비되어 있어야 한다는 뜻입니다.<br>
그래서 2일 전의 각 시간에 대해 7PV를 임계값으로 잡고, 왔다' 또는 '안 왔다'로 분류된 데이터로부터 '온 사람'과 '안 온 사람'의 숫자가 같도록 샘플링합니다.<br> 더욱이 샘플링 후의 데이터를 샘플사이즈를 기준으로 훈련데이터와 테스트데이터로 나늄니다.<br>
나눈 데이터를 가지고 한 유저군의 집합이 되는 훈련데이터로 2일 전의 각 시간대별로 왔을 확률모델을 작성하고, 작성한 모델을 남은 유저군의 테스트데이터에 적용해서 정확도를 확인합니다. 또한 다른 날짜의 데이터를 검증데이터로 삼아서 모델의 예측정확도를 다시 검증합니다.<br>
이번 데이터에 대해서는 각종 커널함수를 사용한 'SVM'과 '랜텀포레스트"  학습기에 의한 예측정확도가 높은 것을 알 수 있었습니다.

In [163]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,f1_score
from sklearn.ensemble import RandomForestClassifier

acc_list=[]
f1_list=[]
for i in range(24):
    features = ['p{}_{}'.format(j, i) for j in range(7)] + ['a_{}'.format(i)]
    # 불균형 데이터-> 균형을 맞추기 위해 데이터 처리
    df1 = train_data[features][train_data[features].iloc[:, -1] == 1]
    df0_orig = train_data[features][train_data[features].iloc[:, -1] == 0]
    df0 = df0_orig.sample(n=df1.shape[0], replace=True)
    df = pd.concat([df1, df0])
    # 모델 학습
    X = df.iloc[:, :-1]
    y = df.iloc[:, -1]
    # y가 균형적으로 뽑힐 수 있게 stratify=y 설정
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0,stratify=y)
    # 랜덤포레스트 모델 학습
    rf = RandomForestClassifier(n_estimators=100, random_state=0)
    rf.fit(X_train, y_train)
    # 모델 예측 및 confusion matrix 출력
    y_pred = rf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)   
    print("Accuracy: {:.4f}".format(acc))
    print("F1 score: {:.4f}".format(f1))
    print("Confusion matrix:\n", cm)
    acc_list.append(acc)
    f1_list.append(f1)

Accuracy: 0.8049
F1 score: 0.7778
Confusion matrix:
 [[19  2]
 [ 6 14]]
Accuracy: 0.6667
F1 score: 0.6957
Confusion matrix:
 [[12  9]
 [ 5 16]]
Accuracy: 0.7059
F1 score: 0.6667
Confusion matrix:
 [[14  3]
 [ 7 10]]
Accuracy: 0.7692
F1 score: 0.7429
Confusion matrix:
 [[17  3]
 [ 6 13]]
Accuracy: 0.7714
F1 score: 0.7647
Confusion matrix:
 [[14  4]
 [ 4 13]]
Accuracy: 0.7576
F1 score: 0.7500
Confusion matrix:
 [[13  4]
 [ 4 12]]
Accuracy: 0.8519
F1 score: 0.8333
Confusion matrix:
 [[13  1]
 [ 3 10]]
Accuracy: 0.7931
F1 score: 0.7692
Confusion matrix:
 [[13  2]
 [ 4 10]]
Accuracy: 0.8333
F1 score: 0.8485
Confusion matrix:
 [[11  4]
 [ 1 14]]
Accuracy: 0.8800
F1 score: 0.8800
Confusion matrix:
 [[11  2]
 [ 1 11]]
Accuracy: 0.6957
F1 score: 0.5882
Confusion matrix:
 [[11  1]
 [ 6  5]]
Accuracy: 0.9231
F1 score: 0.9167
Confusion matrix:
 [[13  0]
 [ 2 11]]
Accuracy: 0.6889
F1 score: 0.6500
Confusion matrix:
 [[18  5]
 [ 9 13]]
Accuracy: 0.7188
F1 score: 0.6667
Confusion matrix:
 [[14  2]
 [

In [164]:
print("acc_mean:",np.mean(acc_list))
print("f1_mean:",np.mean(f1_list))

acc_mean: 0.7715204647901936
f1_mean: 0.7511297769491722


## 액션
이번 데이터 분석은 '자동화,최적화'에 해당하는 장르입니다.<br>
학습기의 예측 정확도를 비교한 결과를 바탕으로 '랜덤포레스트' 학습기를 사용해서 예측모델을 구축하고, 유저별로 내일 어떤 시간대에 어느 정도의 확률로 게임을 이용할 것인지에 관한 데이터를 출력하는 알고리즘을 구현했습니다.<br>
이 결과를 가지고 회의를 한 결과, 어떤 유저가 팀에 가입하려 할 때는 내일 그 유저가 다시 게임을 이용할 예상 시간에 게임을 이용할고 있을 유저가 많은 팀을 추천하는 기능을 추가하기로 했습니다.

## 정리
기계학습을 활용해서 데이터 분석을 실시했습니다.<br>
이번에는 '자동화,최적화'를 염두에 두었고, 데이터를 탐색하는 형식의 데이터 분석이기 때문에 데이터 처리나 가공에 많은 노력이 필요합니다.<br>
예측모델이 잘 만들어졌을 경우, 그 결과를 실제 서비스 개선에 활용하도록 하기 위해 서비스 기획자와 회의나 토론을 꼭 실시해야 합니다. 또한 web 업계에서는 실제로 서비스에 추가되기 때문에 서비스를 개발하는 개발자와도 논의 할 필요가 있습니다.<br>
데이터를 처리하는 내용이 데이터 분석가 이외에는 이해하기 어려운 점이 있습니다.<br>
그러므로 데이터 분석가와 서비스 기획자 간에 충분한 의사소통이 필요합니다.